### PR TITLE
Add Remove silence processor

### PR DESCRIPTION
**Pull request by kevinbird15**
This is my attempt at creating the remove silence processor.  As far as I can tell from my tests, it works.  Here is an example of how it works: 
```
config_split= AudioConfig(remove_silence = "all", silence_padding=200, silence_threshold=20)
rs = RemoveSilenceProcessor(config=config_split)
data = (AudioList.from_folder("data", config=config_split, processor=[rs])
        .use_partial_data(0.01, seed=42)
        .split_by_rand_pct(0.2)
        .label_empty()
        .databunch()
       )
```

### CODE REVIEW

**Comment by mogwai** [comment]
Hi Kevin. This look really good. Can you resolve the conflicts and I will have a play around to see if it works as intended

**Comment by kevinbird15** [comment]
I resolved how I think it should be.  It does stop the messaging from coming through though so if we want messages, we would need to add the messages to the processor.  Let me know if you want me to add that.

**Comment by kevinbird15** [comment]
It would happen at a different spot as well, but it is more in-line with fastai's core functionality

**Comment by kevinbird15** [comment]
Wondering if you've had a chance to play around with this processor and have any feedback on it.

**Comment by mogwai** [comment]
Can't actually pull this branch. Says unknown repository.

**Comment by mogwai** [comment]
Sorry that it took so long for me to review this. 

The remove silence is a one to many method. This method returns multiple wav files that have been split up by the silence in them. Correctly you've noticed that the  `pre_process_one` expects only one item to be returned however your throwing away all the other files that are generated in the directory. I don't think there is a way to use the current `PreProcessor` class to achieve this.

**Pull request closed without merging**
